data_args:
  root: your_root_path
  first_n_secs: 20
  train_ratio: .8
  seed: 4
  feature_type: midi
  n_fft: 2048
  window_type: hann

training_args:
  epochs: 5
  batch_size: 32
  learning_rate: 1.0e-4
  regularization_lambda: 0
  optimizer: adam

inout:
  logdir: name_of_logdir
  ckpt_dir: your_checkpoint_dir
  checkpoint: latest

### Description of parameters ###
#################################
# data_args:
#   root: path to the data
#   first_n_secs: Whether to use only the first_n_secs of audio.
#     Sepcify -1 to use all of the audio. You must make sure all audio have
#     the same amount of samples
#   train_ratio: The train-test split ratio
#   seed: seed for splitting data
#   feature_type: Type of feature for spectrogram, choose between chroma, midi and mfcc
#   n_fft: The number of samples to perform FFT in STFT
#   window_type: The type of window used in STFT. Currently, only hann is available
# training_args:
#   epochs: Total number of training epochs
#   batch_size: self-explanatory
#   learning_rate: see above
#   regularization_lambda: The lambda for L2 regularization, leave 0 for no regularization
#   optimizer: Choose between adam, adamw and sgd
# inout:
#   logdir: A directory with this name will be created in ckpt_dir
#   ckpt_dir: Where the models should be checkpointed
#   checkpoint: Previous checkpoint of the model. Specify latest to load latest checkpoint
#################################