data_args:
  root: your_root_path  # path to the data
  first_n_secs: 20  # Whether to use only the first_n_secs of audio. -1 means use all
  train_ratio: .8  # The train-test split ratio
  feature_type: chroma  # Type of feature for spectrogram: chroma and midi
  n_fft: 2048  # The number of samples to perform FFT in STFT
  window_type: hann  # The type of window used in STFT

training_args:
  epochs: 5
  batch_size: 16
  learning_rate: 1.0e-4
  regularization_lambda: 0  # the lambda for L2 regularization, leave 0 for no regularization
  optimizer: adam  # Choose between adam, adamw and sgd

inout:
  # A directory with this name will be created in ckpt_dir
  logdir: name_of_logdir
  ckpt_dir: your_checkpoint_dir  # where the models should be checkpointed
  checkpoint: latest  # previous checkpoint of the model. Specify latest to load latest checkpoint